#!/usr/bin/env bash
#   Show contents of the file `/etc/passwd`.
#   Show only the username, user id, and user home directory path.

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
